version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: lessons_db
    environment:
      POSTGRES_DB: lessons_db
      POSTGRES_USER: lessons_user
      POSTGRES_PASSWORD: lessons_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./test.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 